package View;

import Estilo.BordaCantoArredondado;
import Model.Carro;
import Model.DAO.CarroDAO;
import com.formdev.flatlaf.FlatLightLaf;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.List;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import Estilo.BotaoRedondo;
import Estilo.TextoMaisculo;
import Style.table.Cabecalho;
import Style.table.Render;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.table.JTableHeader;
import javax.swing.text.AbstractDocument;

public class Agendamentos extends javax.swing.JFrame {

    public Agendamentos() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/48x48.png")));
        
        listaManutencao();
        txtBorda();
        textoMaiusculo();
        
        jScrollPane1.getViewport().setBackground(new java.awt.Color(255, 255, 204));
        jTManutencao.setBackground(new java.awt.Color(255, 255, 204));

        Render render = new Render();
        for (int i = 0; i < jTManutencao.getColumnCount(); i++) {
            jTManutencao.getColumnModel().getColumn(i).setCellRenderer(render);
        }

        JTableHeader header = jTManutencao.getTableHeader();
        header.setDefaultRenderer(new Cabecalho());
    }
    
      public void txtBorda() {
        BordaCantoArredondado bad = new BordaCantoArredondado(Color.GRAY);

        txtDataManutenção.setBorder(bad);
        txtPlaca.setBorder(bad);
        
    }

    public void textoMaiusculo() {
        ((AbstractDocument) txtPlaca.getDocument()).setDocumentFilter(new TextoMaisculo());

    }
    
    public void limparCampos(){
    txtPlaca.setText("");
    txtDataManutenção.setText("");
    
    }
    
    public void listaManutencao(){
    DefaultTableModel modelo = (DefaultTableModel) jTManutencao.getModel();
    
    CarroDAO dao = new CarroDAO();
    List<Carro> manutencao = dao.listaManutencao();
    
    modelo.setRowCount(0);
        for (Carro manutencoes : manutencao) {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            Object[] objeto = new Object[2];
            objeto[0] = manutencoes.getPlaca();
            objeto[1] = sdf.format(manutencoes.getManutencao_agendada());
            modelo.addRow(objeto);
        }
    
    
    }

    public java.sql.Date dataMysql(String data) {
         DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");

        // Converte a string para LocalDate
        LocalDate localDate = LocalDate.parse(data, formatter);

        // Converte LocalDate para java.sql.Date
        return java.sql.Date.valueOf(localDate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDataManutenção = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        btnAgendar = new BotaoRedondo();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTManutencao = new javax.swing.JTable();
        btnFinalizar = new BotaoRedondo();
        btnCancelar = new BotaoRedondo();
        btnAlterar = new BotaoRedondo();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agendamentos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Agendar Manutenção");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Placa do Carro");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        txtPlaca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel2.add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 153, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Data do Agendamento");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        try {
            txtDataManutenção.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataManutenção.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel2.add(txtDataManutenção, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 112, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Informe a placa de um carro já cadastrado");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        btnAgendar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAgendar.setText("Agendar");
        btnAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 110, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 770, 83));

        jTManutencao.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jTManutencao.setForeground(new java.awt.Color(0, 0, 0));
        jTManutencao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PLACA DO CARRO", "DATA DO AGENDAMENTO"
            }
        ));
        jTManutencao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTManutencaoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTManutencao);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 740, 350));

        btnFinalizar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFinalizar.setText("Finalizar Agendamento");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 200, 40));

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar Agendamento");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 200, 40));

        btnAlterar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAlterar.setText("Alterar Data de Agendamento");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 230, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        String placa = txtPlaca.getText();

        Carro carro = new Carro();
        CarroDAO dao = new CarroDAO();

        carro.setManutencao_agendada(null);
        carro.setPlaca(placa);

        dao.cancelarManutencao(carro);
        listaManutencao();
        limparCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarActionPerformed
        // TODO add your handling code here:
        String placa = txtPlaca.getText();

        Carro carro = new Carro();
        CarroDAO dao = new CarroDAO();

        carro.setManutencao_agendada(dataMysql(txtDataManutenção.getText().replace("/","-")));
        carro.setPlaca(placa);

        dao.agendarManutencao(carro);
        listaManutencao();
        limparCampos();
    }//GEN-LAST:event_btnAgendarActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
       

        Carro carro = new Carro();
        CarroDAO dao = new CarroDAO();

        carro.setData_manutencao(dataMysql(txtDataManutenção.getText().replace("/", "-")));
        carro.setPlaca(txtPlaca.getText());
        carro.setManutencao_agendada(null);

        dao.finalizarManutencao(carro);
        listaManutencao();
        limparCampos();
        
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void jTManutencaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTManutencaoMouseClicked
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) jTManutencao.getModel();
        
        int linha = jTManutencao.getSelectedRow();
        txtDataManutenção.setText(modelo.getValueAt(linha, 1).toString());
        txtPlaca.setText(modelo.getValueAt(linha, 0).toString());
    }//GEN-LAST:event_jTManutencaoMouseClicked

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
       String placa = txtPlaca.getText();

        Carro carro = new Carro();
        CarroDAO dao = new CarroDAO();

        carro.setManutencao_agendada(dataMysql(txtDataManutenção.getText().replace("/","-")));
        carro.setPlaca(placa);

        dao.alterarManutencao(carro);
        listaManutencao();
        limparCampos();
    }//GEN-LAST:event_btnAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agendamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgendar;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTManutencao;
    private javax.swing.JFormattedTextField txtDataManutenção;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
