/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import View.CadastroCliente;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;


/**
 *
 * @author lordt
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        btnCadastrarCliente.setBackground(Color.WHITE);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCadastrarCliente = new javax.swing.JButton();
        btnCadastrarCarro = new javax.swing.JButton();
        btnCadastrarPecas = new javax.swing.JButton();
        btnCadastrarMecanico = new javax.swing.JButton();
        btnVendas = new javax.swing.JButton();
        btnBackup = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnOs = new javax.swing.JButton();
        btnVerOs = new javax.swing.JButton();
        btnOrcamento = new javax.swing.JButton();
        btnNotificacoes = new javax.swing.JButton();
        btnContas = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        btnFerramentas = new javax.swing.JButton();
        btnFluxoDeCaixa = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCadastrarCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCadastrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-cliente-48.png"))); // NOI18N
        btnCadastrarCliente.setText("Cadastrar Cliente");
        btnCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadastrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 67));

        btnCadastrarCarro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCadastrarCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-carro-48.png"))); // NOI18N
        btnCadastrarCarro.setText("Cadastrar Carro");
        btnCadastrarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarCarroActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadastrarCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 220, 70));

        btnCadastrarPecas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCadastrarPecas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pecas-de-reposicao.png"))); // NOI18N
        btnCadastrarPecas.setText("Cadastrar Peças");
        btnCadastrarPecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarPecasActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadastrarPecas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 220, 70));

        btnCadastrarMecanico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCadastrarMecanico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mecanico.png"))); // NOI18N
        btnCadastrarMecanico.setText("Cadastrar Mecânico");
        btnCadastrarMecanico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarMecanicoActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadastrarMecanico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 220, 70));

        btnVendas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/caixa-eletronico.png"))); // NOI18N
        btnVendas.setText("Tela de vendas");
        btnVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendasActionPerformed(evt);
            }
        });
        jPanel1.add(btnVendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 220, 70));

        btnBackup.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBackup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/copia-de-seguranca (1).png"))); // NOI18N
        btnBackup.setText("Backup");
        btnBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackupActionPerformed(evt);
            }
        });
        jPanel1.add(btnBackup, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 220, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LOGO-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 460, 410));

        btnOs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnOs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-ordem-48.png"))); // NOI18N
        btnOs.setText("Ordem de Serviço");
        btnOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOsActionPerformed(evt);
            }
        });
        jPanel1.add(btnOs, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 200, 70));

        btnVerOs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVerOs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ordem-de-servico.png"))); // NOI18N
        btnVerOs.setText("Ver Ordens de serviço");
        btnVerOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerOsActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerOs, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 240, -1));

        btnOrcamento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnOrcamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/orcamento (1).png"))); // NOI18N
        btnOrcamento.setText("Orçamento");
        btnOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrcamentoActionPerformed(evt);
            }
        });
        jPanel1.add(btnOrcamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 410, 220, 70));

        btnNotificacoes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNotificacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-notificação-48.png"))); // NOI18N
        btnNotificacoes.setText("Notificações");
        btnNotificacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotificacoesActionPerformed(evt);
            }
        });
        jPanel1.add(btnNotificacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 340, 220, 60));

        btnContas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnContas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pago.png"))); // NOI18N
        btnContas.setText("Contas a pagar");
        btnContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContasActionPerformed(evt);
            }
        });
        jPanel1.add(btnContas, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 270, 220, 60));

        jButton12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-carrinho-de-compras-carregado-48.png"))); // NOI18N
        jButton12.setText("Vendas do dia");
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 204, 220, 60));

        btnFerramentas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFerramentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-ferramentas-48.png"))); // NOI18N
        btnFerramentas.setText("Cadastrar ferramentas");
        btnFerramentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFerramentasActionPerformed(evt);
            }
        });
        jPanel1.add(btnFerramentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 220, -1));

        btnFluxoDeCaixa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFluxoDeCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-vendas-48.png"))); // NOI18N
        btnFluxoDeCaixa.setText("Finanças");
        btnFluxoDeCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFluxoDeCaixaActionPerformed(evt);
            }
        });
        jPanel1.add(btnFluxoDeCaixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 220, -1));

        btnSair.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fechar.png"))); // NOI18N
        btnSair.setText("Fechar sistema");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jPanel1.add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 220, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 934, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarPecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarPecasActionPerformed
        // TODO add your handling code here:
        CadastroPecas cadastroPecas = new CadastroPecas();
        cadastroPecas.setVisible(true);
    }//GEN-LAST:event_btnCadastrarPecasActionPerformed

    private void btnVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendasActionPerformed
        // TODO add your handling code here:
        TelaVenda venda = new TelaVenda();
        this.dispose();
        venda.setVisible(true);
    }//GEN-LAST:event_btnVendasActionPerformed

    private void btnCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarClienteActionPerformed
        // TODO add your handling code here:
        CadastroCliente cadastroCliente = new CadastroCliente();
        cadastroCliente.setVisible(true);
    }//GEN-LAST:event_btnCadastrarClienteActionPerformed

    private void btnCadastrarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarCarroActionPerformed
        // TODO add your handling code here:
        CadastroCarro cadastroCarro = new CadastroCarro();
        cadastroCarro.setVisible(true);
    }//GEN-LAST:event_btnCadastrarCarroActionPerformed

    private void btnCadastrarMecanicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarMecanicoActionPerformed
        // TODO add your handling code here:
        CadastroMecanico cadastroMecanico = new CadastroMecanico();
        cadastroMecanico.setVisible(true);
    }//GEN-LAST:event_btnCadastrarMecanicoActionPerformed

    private void btnContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContasActionPerformed
        // TODO add your handling code here:
        CadastroContas contas = new CadastroContas();
        contas.setVisible(true);
    }//GEN-LAST:event_btnContasActionPerformed

    private void btnOsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOsActionPerformed
        // TODO add your handling code here:
        CadastroOs os = new CadastroOs();
        os.setVisible(true);
    }//GEN-LAST:event_btnOsActionPerformed

    private void btnNotificacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotificacoesActionPerformed
        // TODO add your handling code here:
        this.dispose();
        TelaNotificacoes notificacoes = new TelaNotificacoes();
        notificacoes.setVisible(true);
        
    }//GEN-LAST:event_btnNotificacoesActionPerformed

    private void btnOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrcamentoActionPerformed
        // TODO add your handling code here:
        TelaOrcamento orcamento = new TelaOrcamento();
        orcamento.setVisible(true);
    }//GEN-LAST:event_btnOrcamentoActionPerformed

    private void btnVerOsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerOsActionPerformed
        // TODO add your handling code here:
        VerOSs oss = new VerOSs();
        this.dispose();
        oss.setVisible(true);
    }//GEN-LAST:event_btnVerOsActionPerformed

    private void btnFerramentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFerramentasActionPerformed
        // TODO add your handling code here:
        CadastroFerramenta ferramenta = new CadastroFerramenta();
        ferramenta.setVisible(true);
    }//GEN-LAST:event_btnFerramentasActionPerformed

    private void btnFluxoDeCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFluxoDeCaixaActionPerformed
        // TODO add your handling code here:
        TelaFinanceiro financeiro = new TelaFinanceiro();
        this.dispose();
        financeiro.setVisible(true);
    }//GEN-LAST:event_btnFluxoDeCaixaActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackupActionPerformed
        // TODO add your handling code here:
        TelaBackup backup = new TelaBackup();
        backup.setVisible(true);
    }//GEN-LAST:event_btnBackupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackup;
    private javax.swing.JButton btnCadastrarCarro;
    private javax.swing.JButton btnCadastrarCliente;
    private javax.swing.JButton btnCadastrarMecanico;
    private javax.swing.JButton btnCadastrarPecas;
    private javax.swing.JButton btnContas;
    private javax.swing.JButton btnFerramentas;
    private javax.swing.JButton btnFluxoDeCaixa;
    private javax.swing.JButton btnNotificacoes;
    private javax.swing.JButton btnOrcamento;
    private javax.swing.JButton btnOs;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnVendas;
    private javax.swing.JButton btnVerOs;
    private javax.swing.JButton jButton12;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
