package View;

import Model.DAO.FluxoDeCaixaDAO;
import Model.FluxoDeCaixa;
import Style.table.Cabecalho;
import Style.table.Render;
import com.formdev.flatlaf.FlatLightLaf;
import java.text.DecimalFormat;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author MadaraX4
 */
public class TelaFinanceiro extends javax.swing.JFrame {

    /**
     * Creates new form TelaFinanceiro
     */
    public TelaFinanceiro() {
        initComponents();

        Timer timer = new Timer(1000, e -> relogio());
        timer.start();

        colunaTabela();

        jScrollPane1.getViewport().setBackground(new java.awt.Color(255, 255, 204));
        jTFluxoDeCaixa.setBackground(new java.awt.Color(255, 255, 204));

        Render render = new Render();
        for (int i = 0; i < jTFluxoDeCaixa.getColumnCount(); i++) {
            jTFluxoDeCaixa.getColumnModel().getColumn(i).setCellRenderer(render);
        }

        JTableHeader header = jTFluxoDeCaixa.getTableHeader();
        header.setDefaultRenderer(new Cabecalho());

        listaFluxo();
        totalEntrada();
        totalSaida();
    }

    public void relogio() {
        LocalTime horaAtual = LocalTime.now();
        DateTimeFormatter df = DateTimeFormatter.ofPattern("HH:mm:ss");
        lblHora.setText(df.format(horaAtual));

    }

    public void colunaTabela() {
        jTFluxoDeCaixa.getColumnModel().getColumn(0).setPreferredWidth(200);
        jTFluxoDeCaixa.getColumnModel().getColumn(1).setPreferredWidth(30);
        jTFluxoDeCaixa.getColumnModel().getColumn(2).setPreferredWidth(30);
        jTFluxoDeCaixa.getColumnModel().getColumn(3).setPreferredWidth(30);
        jTFluxoDeCaixa.getColumnModel().getColumn(4).setPreferredWidth(20);
        jTFluxoDeCaixa.getColumnModel().getColumn(5).setPreferredWidth(20);
    }

    public void listaFluxo() {

        DefaultTableModel modelo = (DefaultTableModel) jTFluxoDeCaixa.getModel();
        FluxoDeCaixaDAO dao = new FluxoDeCaixaDAO();

        List<FluxoDeCaixa> lista = dao.listaFluxo();

        for (FluxoDeCaixa fluxoDeCaixa : lista) {
            Object[] objeto = new Object[6];
            DateTimeFormatter dfData = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            DecimalFormat decimal = new DecimalFormat("###0.00");
            objeto[0] = fluxoDeCaixa.getDescricao();
            objeto[1] = fluxoDeCaixa.getTipo();
            objeto[2] = dfData.format(fluxoDeCaixa.getDataOperacao());
            objeto[3] = fluxoDeCaixa.getHoraOperacao();
            objeto[4] = decimal.format(fluxoDeCaixa.getValorEntrada());
            objeto[5] = decimal.format(fluxoDeCaixa.getValorSaida());
            modelo.addRow(objeto);
        }

    }

    public void totalEntrada() {
        DefaultTableModel modelo = (DefaultTableModel) jTFluxoDeCaixa.getModel();

        double soma = 0;
        int coluna = 4;

        for (int i = 0; i < modelo.getRowCount(); i++) {
            Object valor = modelo.getValueAt(i, coluna);
            if (valor != null && valor instanceof String) {
                String valorString = (String) valor;
                valorString = valorString.replace(",", ".");
                try {
                    soma += Double.parseDouble(valorString);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }

        }
        //System.out.println(soma);
        DecimalFormat df = new DecimalFormat("#,##0.00");
        txtTotalEntrada.setText(df.format(soma));

    }

    public void totalSaida() {

        DefaultTableModel modelo = (DefaultTableModel) jTFluxoDeCaixa.getModel();
        double soma = 0;
        int coluna = 5;

        for (int i = 0; i < modelo.getRowCount(); i++) {
            Object valor = modelo.getValueAt(i, coluna);

            if (valor != null && valor instanceof String) {
                String valorString = (String) valor;
               valorString = valorString.replace(",", "."); // substitui vírgula por ponto
               

                try {
                    soma += Double.parseDouble(valorString);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }

        DecimalFormat df = new DecimalFormat("#,##0.00");
        txtTotalSaida.setText(df.format(soma));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTFluxoDeCaixa = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtTotalEntrada = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTotalSaida = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(153, 255, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Financeiro");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, -1, -1));

        lblHora.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblHora.setForeground(new java.awt.Color(0, 0, 0));
        lblHora.setText("Hora");
        jPanel2.add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 150, 30));

        btnSair.setBackground(new java.awt.Color(255, 255, 204));
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/perto.png"))); // NOI18N
        btnSair.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jPanel2.add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, 70, 30));

        jTFluxoDeCaixa.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jTFluxoDeCaixa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DESCRIÇÃO", "TIPO", "DATA", "HORA", "VALOR ENTRADA", "VALOR DE SAIDA"
            }
        ));
        jScrollPane1.setViewportView(jTFluxoDeCaixa);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("VALOR TOTAL DE ENTRADAS DO MÊS");

        txtTotalEntrada.setEditable(false);
        txtTotalEntrada.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("VALOR TOTAL DE SAIDAS DO MÊS");

        txtTotalSaida.setEditable(false);
        txtTotalSaida.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotalEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtTotalSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTotalEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtTotalSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        TelaInicial inicial = new TelaInicial();
        this.dispose();
        inicial.setVisible(true);
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFinanceiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTFluxoDeCaixa;
    private javax.swing.JLabel lblHora;
    private javax.swing.JTextField txtTotalEntrada;
    private javax.swing.JTextField txtTotalSaida;
    // End of variables declaration//GEN-END:variables
}
